term.clear()
term.setCursorPos(1,1)

print("List of installed systen commands (6).")
print("Commands - full list of commands.")
print("Clean - Cleans your system for you.")
print("update - updater.")
print("fetch - Shows information about the system.")
print("exit - exits custom shell.")
print("power - Shows power options.")